# Generated by Django 4.1.3 on 2023-08-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapID', models.TextField()),
                ('location', models.CharField(max_length=100, null=True)),
                ('profile_of_needs', models.CharField(max_length=100, null=True)),
                ('registered_providers', models.TextField(null=True)),
                ('care_providers', models.TextField(null=True)),
                ('icb_contacts', models.TextField(null=True)),
                ('void_agreement', models.TextField(null=True)),
                ('additional_notes', models.TextField(null=True)),
                ('color', models.TextField(null=True)),
            ],
        ),
    ]
